image: alpine/edge
secrets:
  - 47d24bc3-7269-4797-9cc3-5fee7d5b66f6    # Set your UUID here!
environment:
  REPO: dotf
  GH_USER: tjex
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
