image: alpine/edge
secrets:
  - 39e1fed3-33e0-48c8-ae8b-ad741cc3cdb9    # Set your UUID here!
environment:
  REPO: dotf
  GH_USER: tjex
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
