image: alpine/edge
secrets:
  - 91bfe501-d4ff-4aeb-b14a-9b9790957dc7    # Set your UUID here!
environment:
  REPO: dotf
  GH_USER: tjex
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
