image: alpine/edge
secrets:
  - 258e373b-25c5-469d-a9a0-f41e48650f11
sources:
  - git@git.sr.ht/~tjex/dotf
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      # This is for not having to cd into your <repo> for each task
      echo 'cd <repo>' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:tjex/dotf.git
